services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
    volumes:
      - config:/config
      - torrent:/torrent
      - themes:/themes
    networks:
      - frontend
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
volumes:
  config:
    name: qbittorrent_config
  torrent:
    name: data_torrent
    external: true
  themes:
    name: qbittorrent_themes
networks:
  frontend:
    external: true
