services:
  filebot:
    image: jlesage/filebot:latest
    container_name: filebot
    environment:
      USER_ID: ${PUID}
      GROUP_ID: ${PGID}
      TZ: ${TZ}
      DARK_MODE: 1
    ports:
      - 5800:5800 #web ui
    volumes:
      - config:/config:rw
      - storage:/storage:rw
      - watch:/watch:rw
      - output:/output:rw
    restart: unless-stopped
volumes:
  config:
    name: filebot_config
    driver: local-persist
    driver_opts:
      mountpoint: ${LP_CONFIG}
  storage:
    name: filebot_storage
    driver: local-persist
    driver_opts:
      mountpoint: ${LP_STORAGE}
  watch:
    name: filebot_watch
    driver: local-persist
    driver_opts:
      mountpoint: ${LP_WATCH}
  output:
    name: filebot_output
    driver: local-persist
    driver_opts:
      mountpoint: ${LP_OUTPUT}
