services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri #hardware acceleration
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_LOG_DEBUG=1
      - FILE__PLEX_CLAIM=/run/secrets/claim
      #- FILE__PLEX_CLAIM=/run/secrets/claim
    volumes:
      - config:/config
      - media:/media
    restart: unless-stopped

volumes:
  config:
    name: plex_config
  media:
    name: nfs_media
    external: true

secrets:
  claim:
    file: ${SECRETS}/plex.claim