services:
  plex:
    #image: lscr.io/linuxserver/plex:latest # wud couldnt handle lscr.io being on there...
    image: linuxserver/plex
    container_name: plex
    ports:
      # Plex DLNA Server
      - 32400:32400/tcp
      - 32400:32400/udp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    networks:
      - frontend
    devices:
      - /dev/dri:/dev/dri # hardware acceleration
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      VERSION: docker
      # PLEX_LOG_DEBUG: '1'  # Disabled - excessive logging
      FILE__PLEX_CLAIM: /run/secrets/claim
    volumes:
      - config:/config
        #- media:/media
      - data:/data
      - /tmp/plex-transcode:/transcode # Transcoding temp directory, control where transcodes are stored
      # Default Linux only allocates a max of 50% of total system RAM to any ram directories (ie. /tmp, /dev/shm, etc.)

    secrets:
      - claim
    labels:
      traefik.enable: 'true'
      traefik.http.routers.plex.rule: 'Host(`plex.in.rounds.house`)'
      traefik.http.routers.plex.entrypoints: 'https'
      traefik.http.routers.plex.tls: 'true'
      traefik.http.services.plex.loadbalancer.server.port: '32400'

      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.link.template: 'https://github.com/linuxserver/docker-plex/releases'
      wud.display.name: 'Plex'
      wud.display.icon: 'sh:plex'
    restart: unless-stopped

volumes:
  config:
    name: plex_config
  data:
    name: nfs_data
    external: true

secrets:
  claim:
    file: ${SECRETS}/plex.claim

networks:
  frontend:
    external: true
