services:
  bind9:
    image: ubuntu/bind9:9.18-24.04_beta
    container_name: bind9
    environment:
      BIND9_USER: bind
      TZ: "${TZ}"
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    volumes:
      - ./config:/etc/bind
      - cache:/var/cache/bind
    networks:
      - backend
    labels:
      wud.tag.include: '^\d+\.\d+-\d+\.\d+_(beta|candidate|stable)$$'
      wud.display.name: 'Bind9'
      wud.display.icon: 'mdi:dns-outline'
    restart: unless-stopped

volumes:
  cache:
    name: bind9_cache

networks:
  backend:
    external: true
