services:
  mosquitto:
    build: .
    image: eclipse-mosquitto-auth-secrets:2.0.18
    container_name: mosquitto
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      MOSQUITTO_USERNAME: ${MOSQUITTO_USERNAME}
      MOSQUITTO_PASSWORD_FILE: /run/secrets/password
    restart: unless-stopped
    secrets:
      - password
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - backend
    volumes:
      - log:/mosquitto/log
      - data:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro #read only so that the container doesnt change permissions
volumes:
  log:
    name: mosquitto_log
  data:
    name: mosquitto_data
secrets:
  password:
    file: ${SECRETS}/mosquitto.password.mos

networks:
  backend:
    external: true