services:
  mosquitto:
    build: .
    image: eclipse-mosquitto-auth-secrets:2.0.18
    container_name: mosquitto
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      MOSQUITTO_USERNAME: mos
      MOSQUITTO_PASSWORD_FILE: /run/secrets/password
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -t '$$SYS/#' -C 1 -W 3 -u mos -P \"$$(cat /run/secrets/password)\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    mem_limit: 64m
    mem_reservation: 32m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    restart: unless-stopped
    secrets:
      - password
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - backend
    volumes:
      - log:/mosquitto/log
      - data:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro #read only so that the container doesnt change permissions
volumes:
  log:
    name: mosquitto_log
  data:
    name: mosquitto_data
secrets:
  password:
    file: ${SECRETS}/mosquitto.password.mos

networks:
  backend:
    external: true