services:
  traefik:
    image: traefik:v3.2
    container_name: traefik
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      DNSIMPLE_OAUTH_TOKEN_FILE: /run/secrets/dnsimple_oauth_token
    secrets:
      - dnsimple_oauth_token
      - traefik_dashboard_credentials
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./config.yml:/config/config.yml:ro
      - letsencrypt:/letsencrypt
    networks:
      - socket-proxy
      - frontend
    labels:
      traefik.enable: 'true'

      # HTTP Router for Redirection
      traefik.http.routers.traefik-http.rule: 'Host(`traefik.in.rounds.house`)'
      traefik.http.routers.traefik-http.entrypoints: 'http'
      traefik.http.routers.traefik-http.middlewares: 'redirect-to-https'
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: 'https'

      # HTTPS Router for Traefik Dashboard
      traefik.http.routers.traefik.rule: 'Host(`traefik.in.rounds.house`)'
      traefik.http.routers.traefik.entrypoints: 'https'
      traefik.http.routers.traefik.tls: 'true'
      traefik.http.routers.traefik.tls.certresolver: 'dnsimple'
      traefik.http.routers.traefik.tls.domains[0].main: 'in.rounds.house'
      traefik.http.routers.traefik.tls.domains[0].sans: '*.in.rounds.house'

      # Define the service as internal API (Traefik Dashboard)
      traefik.http.routers.traefik.service: 'api@internal'

      wud.tag.include: '^v\d+\.\d+\.\d+$$'
      wud.link.template: 'https://github.com/traefik/traefik/releases/tag/v$${major}.$${minor}.$${patch}'
      wud.display.name: 'Traefik'
      wud.display.icon: 'sh:traefik'
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  socket-proxy:
    external: true
  frontend:
    external: true

volumes:
  letsencrypt:
    name: traefik_letsencrypt

secrets:
  dnsimple_oauth_token:
    file: ${SECRETS}/traefik.dnsimple.token
  traefik_dashboard_credentials:
    file: ${SECRETS}/traefik.dashboard.credentials