services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      HOMEPAGE_ALLOWED_HOSTS: "in.rounds.house"
      HOMEPAGE_FILE_PORTAINER_KEY: /run/secrets/portainer_key
      HOMEPAGE_FILE_QBITTORRENT_USERNAME: /run/secrets/qbittorrent_username
      HOMEPAGE_FILE_QBITTORRENT_PASSWORD: /run/secrets/qbittorrent_password
      HOMEPAGE_FILE_PLEX_KEY: /run/secrets/plex_key
      HOMEPAGE_FILE_PVE_USERNAME: /run/secrets/pve_username
      HOMEPAGE_FILE_PVE_PASSWORD: /run/secrets/pve_password
      HOMEPAGE_FILE_GRAFANA_USERNAME: /run/secrets/grafana_username
      HOMEPAGE_FILE_GRAFANA_PASSWORD: /run/secrets/grafana_password
      HOMEPAGE_FILE_PROWLARR_KEY: /run/secrets/prowlarr_key
      HOMEPAGE_FILE_RADARR_KEY: /run/secrets/radarr_key
      HOMEPAGE_FILE_RADARR_4K_KEY: /run/secrets/radarr_4k_key
      HOMEPAGE_FILE_SONARR_KEY: /run/secrets/sonarr_key
      HOMEPAGE_FILE_SONARR_4K_KEY: /run/secrets/sonarr_4k_key
      HOMEPAGE_FILE_BAZARR_KEY: /run/secrets/bazarr_key
      HOMEPAGE_FILE_BAZARR_4K_KEY: /run/secrets/bazarr_4k_key
      HOMEPAGE_FILE_OVERSEERR_KEY: /run/secrets/overseerr_key
      HOMEPAGE_FILE_SABNZBD_KEY: /run/secrets/sabnzbd_key
      HOMEPAGE_FILE_UNIFI_USERNAME: /run/secrets/unifi_username
      HOMEPAGE_FILE_UNIFI_PASSWORD: /run/secrets/unifi_password
    secrets:
      - portainer_key
      - qbittorrent_username
      - qbittorrent_password
      - plex_key
      - pve_username
      - pve_password
      - grafana_username
      - grafana_password
      - prowlarr_key
      - radarr_key
      - radarr_4k_key
      - sonarr_key
      - sonarr_4k_key
      - bazarr_key
      - bazarr_4k_key
      - overseerr_key
      - sabnzbd_key
      - unifi_username
      - unifi_password
    ports:
      - '3001:3000'
    volumes:
      - ./config:/app/config:rw
      - ./icons:/app/public/icons
    networks:
      - frontend
    labels:
      traefik.enable: 'true'
      traefik.http.routers.homepage.rule: 'Host(`in.rounds.house`)'
      traefik.http.routers.homepage.entrypoints: 'https'
      traefik.http.routers.homepage.tls: 'true'
      traefik.http.services.homepage.loadbalancer.server.port: '3000'
      traefik.docker.network: 'frontend'

      wud.link.template: 'https://github.com/gethomepage/homepage/releases'
      wud.display.name: 'Homepage'
      wud.display.icon: 'sh:homepage'
    security_opt:
      - no-new-privileges:true
    mem_limit: 256m
    mem_reservation: 128m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    restart: unless-stopped

networks:
  frontend:
    external: true

secrets:
  portainer_key:
    file: ${SECRETS}/homepage.portainer.key
  qbittorrent_username:
    file: ${SECRETS}/qbittorrent.username
  qbittorrent_password:
    file: ${SECRETS}/qbittorrent.password
  plex_key:
    file: ${SECRETS}/plex.key
  pve_username:
    file: ${SECRETS}/pve.api.username
  pve_password:
    file: ${SECRETS}/pve.api.password
  grafana_username:
    file: ${SECRETS}/grafana.username
  grafana_password:
    file: ${SECRETS}/grafana.password
  prowlarr_key:
    file: ${SECRETS}/homepage.prowlarr.key
  radarr_key:
    file: ${SECRETS}/homepage.radarr.key
  radarr_4k_key:
    file: ${SECRETS}/homepage.radarr-4k.key
  sonarr_key:
    file: ${SECRETS}/homepage.sonarr.key
  sonarr_4k_key:
    file: ${SECRETS}/homepage.sonarr-4k.key
  bazarr_key:
    file: ${SECRETS}/homepage.bazarr.key
  bazarr_4k_key:
    file: ${SECRETS}/homepage.bazarr-4k.key
  overseerr_key:
    file: ${SECRETS}/homepage.overseerr.key
  sabnzbd_key:
    file: ${SECRETS}/homepage.sabnzbd.key
  unifi_username:
    file: ${SECRETS}/homepage.unifi.username
  unifi_password:
    file: ${SECRETS}/homepage.unifi.password
