services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    ports:
      - 3001:3000
    volumes:
      - config:/app/config:rw
    networks:
      - frontend
    restart: unless-stopped
volumes:
  config:
    name: homepage_config

networks:
  frontend:
    external: true