version: '3.7'
services:
  flexget:
    image: lscr.io/linuxserver/flexget:latest
    container_name: flexget
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      FG_LOG_LEVEL: info
      FG_LOG_FILE: /config/flexget.log
      FG_CONFIG_FILE: /config/config.yml
      FILE__FG_WEBUI_PASSWORD: /run/secrets/password
    volumes:
      - config:/config
      - data:/data
    secrets:
      - password
    ports:
      - 5050:5050
    restart: unless-stopped
volumes:
  config:
    name: flexget_config
    driver: local-persist
    driver_opts:
      mountpoint: ${LP_CONFIG}
  data:
    name: flexget_data
    driver: local-persist
    driver_opts:
      mountpoint: ${DATA}
secrets:
  password:
    file: ${SECRETS}/flexget.password