services:
  filebot:
    container_name: filebot-projector
    image: rednoah/filebot:projector
    restart: unless-stopped
    ports:
      - 8887:8887
    volumes:
      - data:/data
      - output:/output
      - input:/input
      - test:/test
    networks:
      - frontend
    labels:
      traefik.enable: 'true'
      traefik.http.routers.filebot-projector.rule: 'Host(`filebot-projector.in.rounds.house`)'
      traefik.http.routers.filebot-projector.entrypoints: 'https'
      traefik.http.routers.filebot-projector.tls: 'true'
      traefik.http.services.filebot-projector.loadbalancer.server.port: '8887'
      traefik.docker.network: 'frontend'

volumes:
  data:
    name: filebot-xpra_data
    external: true
  output:
    name: nfs_media
    external: true
  input:
    name: nfs_torrent
    external: true

networks:
  frontend:
    external: true