services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      AUTO_UPDATE: "true" #optional or something
      RUN_OPTS: #optional
    volumes:
      - config:/config
      - downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.in.rounds.house`)"
      - "traefik.http.routers.jackett.entrypoints=https"
      - "traefik.http.routers.jackett.tls=true"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
      - "traefik.docker.network=frontend"
volumes:
  config:
    name: jackett_config
    driver: local-persist
    driver_opts:
      mountpoint: ${LOCAL_PERSIST}/jackett/config
  downloads:
    name: jackett_downloads
    driver: local-persist
    driver_opts:
      mountpoint: ${LOCAL_PERSIST}/jackett/downloads

networks:
  frontend:
    external: true