services:
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: socket-proxy
    environment:
      - ALLOW_START=1 # Portainer
      - ALLOW_STOP=1 # Portainer
      - ALLOW_RESTARTS=1 # Portainer
      - AUTH=0
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik, portainer, etc.
      - DISABLE_IPV6=0
      - DISTRIBUTION=0
      - EVENTS=1 # default
      - EXEC=0
      - IMAGES=1 # Portainer
      - INFO=1 # Portainer
      - NETWORKS=1 # Portainer
      - NODES=0
      - PING=1 # default
      - POST=1 #Watchtower
      - PLUGINS=0
      - SECRETS=0 #optional
      - SERVICES=1 # Portainer
      - SESSION=0
      - SWARM=0 
      - SYSTEM=0
      - TASKS=1 # Portainer
      - VERSION=1 # default
      - VOLUMES=1 # Portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run
    networks:
      - socket-proxy
    ports:
      - "2375:2375"
    labels:
      wud.link.template: 'https://github.com/linuxserver/docker-socket-proxy/releases'
      wud.display.name: 'Docker Socket Proxy'
      wud.display.icon: 'mdi:connection'

networks:
  socket-proxy:
    name: socket-proxy