# version: "3"

services:
  file-browser:
    container_name: file-browser
    image: hurlenko/filebrowser
    user: "${PUID}:${PGID}"
    ports:
      - 8081:8080
    volumes:
      - torrent:/data/torrent
      - config:/config
      # - qbittorrent_themes:/data/qbittorrent_themes
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.file-browser.rule=Host(`filebrowser.in.rounds.house`)"
      - "traefik.http.routers.file-browser.entrypoints=https"
      - "traefik.http.routers.file-browser.tls=true"
      - "traefik.http.services.file-browser.loadbalancer.server.port=8080"
      - "traefik.docker.network=frontend"

volumes:
  config:
    name: file-browser_config
  torrent:
    name: data_torrent
    external: true

networks:
  frontend:
    external: true
  backend:
    external: true