# version: "3"

services:
  file-browser:
    container_name: file-browser
    image: hurlenko/filebrowser
    user: "${PUID}:${PGID}"
    ports:
      - 8081:8080
    volumes:
      - torrent:/data/torrent
      - config:/config
      - qbittorrent_themes:/data/qbittorrent_themes
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped

volumes:
  config:
    name: file-browser_config
  torrent:
    name: data_torrent
    external: true
  qbittorrent_themes:
    name: qbittorrent_themes
    external: true
