version: '3.7'
services:
  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:9.20.0
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      - TZ=${TZ}
    networks:
      - backend
      - frontend
    devices:
      # Use the /dev/serial/by-id/X serial device for Z-Wave stick.
      - '/dev/serial/by-id/usb-Zooz_800_Z-Wave_Stick_533D004242-if00:/dev/zwave'
    volumes:
      - config:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zwave-js-ui.rule=Host(`zwave.in.rounds.house`)"
      - "traefik.http.routers.zwave-js-ui.entrypoints=https"
      - "traefik.http.routers.zwave-js-ui.tls=true"
      - "traefik.http.services.zwave-js-ui.loadbalancer.server.port=8091"
      - "traefik.docker.network=frontend"

networks:
  backend:
    external: true
  frontend:
    external: true

volumes:
  config:
    name: zwave-js-ui_config
