services:
  filebot:
    image: rednoah/filebot:watcher
    container_name: filebot-watcher
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      SETTLE_DOWN_TIME: '300'
    volumes:
      - data:/data
      - input:/input
      - output:/output
    command: "${COMMAND}"
    labels:
      wud.link.template: 'https://github.com/filebot/filebot-docker'
      wud.display.name: 'FileBot Watcher'
      wud.display.icon: 'mdi:robot'
    restart: unless-stopped

volumes:
  data:
    name: filebot-watcher_data
  output:
    name: nfs_media
    external: true
  input:
    name: data_torrent
    external: true