services:
  filebot:
    container_name: filebot-watcher
    image: rednoah/filebot:watcher
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      SETTLE_DOWN_TIME: 300
    volumes:
      - data:/data
      - input:/input
      - output:/output
    command: ${COMMAND}
volumes:
  data:
    name: filebot-watcher_data
  output:
    name: nfs_media
    external: true
  input:
    name: data_torrent
    external: true