services:
  filebot:
    container_name: filebot-watcher
    image: rednoah/filebot:watcher
    restart: unless-stopped
    volumes:
      - data:/data
      - output:/volume1
      - input/download:/input
    command: ${COMMAND}
volumes:
  data:
    name: filebot-watcher_data
  output:
    name: nfs_test #nfs_media
    external: true
  input:
    name: data_torrent
    external: true