FROM nodered/node-red

RUN npm install node-red-contrib-actionflows \
        # https://flows.nodered.org/node/node-red-contrib-actionflows
	node-red-contrib-home-assistant-websocket \
        # https://flows.nodered.org/node/node-red-contrib-home-assistant-websocket
	node-red-contrib-stoptimer \
        # https://flows.nodered.org/node/node-red-contrib-stoptimer
	node-red-contrib-time-range-switch \
        # A simple Node-RED node that routes messages depending on the time. If the current time falls within the range specified in the node configuration, the message is routed to output 1. Otherwise the message is routed to output 2.
	node-red-contrib-timecheck \
        # Is it that time yet? This node compares a given time to the current time.
        node-red-contrib-bigtimer \
        # BigTimer is the best Node-Red timing node offering a range of timing facilities
        node-red-contrib-schedex \
        # Scheduler for node-red which allows you to enter on/off times as 24hr clock (e.g. 01:10) or suncalc events
	node-red-node-timeswitch \
        # node to provide a simple timeswitch node to schedule daily on/off events
        node-red-contrib-huemagic \
        # HueMagic provides several input and output nodes for Node-RED and is the most in-depth and easy to use solution to control Philips Hue bridges, lights, groups, scenes, rules, taps, switches, buttons, motion sensors, temperature sensors and Lux sensors.
        node-red-contrib-uibuilder \
        # Easily create web UI's for Node-RED using any (or no) front-end library. VueJS and bootstrap-vue included but change as desired.
        node-red-dashboard
        # This module provides a set of nodes in Node-RED to quickly create a live data dashboard.
