version: "3.7"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.20.3-alpine
    restart: always
    environment:
      TZ: ${TZ}
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
volumes:
  data:
    name: portainer_data
    driver: local-persist
    driver_opts:
      mountpoint: ${LOCAL_PERSIST}/portainer/data
