services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - config:/config
      - data:/data
    ports:
      - 6767:6767
    networks:
      - frontend
    restart: unless-stopped
    labels:
      traefik.enable: 'true'
      traefik.http.routers.bazarr.rule: 'Host(`bazarr.in.rounds.house`)'
      traefik.http.routers.bazarr.entrypoints: 'https'
      traefik.http.routers.bazarr.tls: 'true'
      traefik.http.services.bazarr.loadbalancer.server.port: '6767'
      traefik.docker.network: 'frontend'

      wud.link.template: 'https://github.com/linuxserver/docker-bazarr/releases'
      wud.display.name: 'bazarr'
      wud.display.icon: 'sh:bazarr'

volumes:
  config:
    name: bazarr_config
  media:
    name: nfs_media
    external: true
  data:
    name: nfs_data
    external: true
networks:
  frontend:
    external: true