services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - config:/config
      - data1:/data1
      - data2:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

volumes:
  config:
    name: syncthing_config
    driver: local-persist
    driver_opts:
      mountpoint: ${LP_CONFIG}
  data1:
    name: syncthing_data1
    driver: local-persist
    driver_opts:
      mountpoint: ${LOCAL_PERSIST}
  data2:
    name: syncthing_data2
    driver: local-persist
    driver_opts:
      mountpoint: /home/