---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- unifi_console:
    url: https://10.10.10.1
    username: {{HOMEPAGE_FILE_UNIFI_USERNAME}}
    password: {{HOMEPAGE_FILE_UNIFI_PASSWORD}}
    
- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

