services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.40.1
    container_name: zigbee2mqtt
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    user: ${PUID}:${PGID}
    volumes:
      - data:/app/data
    ports:
      - 8383:8080
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zigbee2mqtt.rule=Host(`zigbee.in.rounds.house`)"
      - "traefik.http.routers.zigbee2mqtt.entrypoints=https"
      - "traefik.http.routers.zigbee2mqtt.tls=true"
      - "traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8080"
      - "traefik.docker.network=frontend"

volumes:
  data:
    name: zigbee2mqtt_data
    external: true

networks:
  frontend:
    external: true
  backend:
    external: true